# Generated by Django 2.2.6 on 2019-11-06 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldate',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.Reservation'),
        ),
    ]
